[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

# WordPress API Proxy Rules (Order matters!)
[[redirects]]
  from = "/graphql"
  to = "https://wp.violetrainwater.com/graphql"
  status = 200
  force = true
  headers = {X-From = "Netlify", X-Proxy = "WordPress-GraphQL"}

[[redirects]]
  from = "/wp-json/*"
  to = "https://wp.violetrainwater.com/wp-json/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", X-Proxy = "WordPress-REST"}

[[redirects]]
  from = "/wp-content/*"
  to = "https://wp.violetrainwater.com/wp-content/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", X-Proxy = "WordPress-Assets"}

[[redirects]]
  from = "/wp-admin/*"
  to = "https://wp.violetrainwater.com/wp-admin/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", X-Proxy = "WordPress-Admin"}

[[redirects]]
  from = "/wp-login.php"
  to = "https://wp.violetrainwater.com/wp-login.php"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "https://wp.violetrainwater.com/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "https://wp.violetrainwater.com/robots.txt"
  status = 200
  force = true

# MUST BE LAST: Catch-all for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers - FIXED for iframe embedding
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = ""
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'self' https://wp.violetrainwater.com https://violetrainwater.com https://www.violetrainwater.com https://lustrous-dolphin-447351.netlify.app http://localhost:* https://*.violetrainwater.com"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
